import type { Metadata } from 'next';
import { Badge } from '@/components/ui/badge';

export const metadata: Metadata = {
  title: 'Methodology',
  description: 'AIVEX evaluation-first approach to AI signal research — confidence scoring, governance, and data quality.',
};

export default function MethodologyPage() {
  return (
    <div className="py-16">
      <div className="container mx-auto max-w-4xl px-4">
        <div className="mb-12 text-center">
          <Badge variant="accent" className="mb-4">Research Framework</Badge>
          <h1 className="mb-4 text-4xl font-bold">Methodology</h1>
          <p className="text-lg text-muted-foreground">
            How AIVEX approaches signal generation, evaluation, and governance.
          </p>
        </div>

        <div className="prose">
          <h2>Evaluation-First Design</h2>
          <p>
            AIVEX was built with evaluation as the primary concern, not prediction. Every signal
            module is required to produce a confidence score alongside its output, and every
            composition step must be reproducible from the same inputs.
          </p>
          <p>
            This means we prioritize falsifiability: a signal that cannot be evaluated against a
            ground truth is not a signal — it is speculation. Our backtesting harness runs
            continuously against historical data to validate that module outputs remain well-calibrated.
          </p>

          <h2>Signal Governance</h2>
          <h3>Confidence Scoring</h3>
          <p>
            Each atomic signal module produces a scalar confidence value in [0, 1]. Confidence is
            derived from multiple factors: source reliability, signal agreement across independent
            feeds, recency of underlying data, and historical calibration error.
          </p>
          <p>
            Signals below a configurable minimum confidence threshold (default: 0.35) are filtered
            before reaching the composition layer. This prevents low-quality inputs from polluting
            the composite signal.
          </p>

          <h3>Cooldown Logic</h3>
          <p>
            To prevent signal churn, each module enforces a per-symbol cooldown period after emitting
            a signal. During cooldown, new signals for the same symbol are suppressed unless their
            confidence exceeds the previous signal by a configurable margin (default: 0.15).
          </p>
          <p>
            Cooldown periods are adaptive: higher-volatility periods automatically shorten cooldown
            windows to allow faster signal updates.
          </p>

          <h3>Governor Gating</h3>
          <p>
            The Governor is the final checkpoint before any signal reaches the API. It applies:
          </p>
          <ul>
            <li><strong>Hard limits:</strong> Symbol-level exposure caps and sector concentration limits</li>
            <li><strong>Kill switch:</strong> Global disable flag controllable via environment variable</li>
            <li><strong>Human override:</strong> Manually blocked symbols are excluded for a configurable window</li>
            <li><strong>Audit logging:</strong> Every gating decision — allow or deny — is logged with full context</li>
          </ul>

          <h2>Data Quality Principles</h2>
          <p>
            AIVEX enforces strict data quality checks at ingestion:
          </p>
          <ul>
            <li>All timestamps are normalized to UTC with microsecond precision</li>
            <li>Price data is validated against exchange-reported OHLCV bounds</li>
            <li>News sources are scored for historical reliability and deduplicated by content hash</li>
            <li>Stale data (age exceeding configurable threshold) is quarantined, not silently used</li>
          </ul>

          <h2>Research Disclaimers</h2>
          <div className="not-prose rounded-xl border border-border bg-muted/30 p-6">
            <p className="text-sm text-muted-foreground">
              <strong>Important:</strong> All outputs generated by AIVEX are for research and
              informational purposes only. They do not constitute financial, investment, trading, or
              any other form of professional advice. Past signal performance does not guarantee future
              results. AIVEX Analytics is not a registered investment advisor, broker-dealer, or
              commodity trading advisor. Users are responsible for their own investment decisions.
            </p>
            <p className="mt-3 text-sm text-muted-foreground">
              Signal outputs may contain errors, omissions, or outdated information. AIVEX Analytics
              makes no representations or warranties regarding the accuracy, completeness, or
              timeliness of any research output.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
